### ISSUE TITLE
502 on first load after appengine sleep

### ISSUE THREAD

**Issue by s-mang** [womenwhogo/womenwhogo.org#12]
this is totally speculating;
i got a 502 (I think?) for a split second around 4:40PM Pacific Time.
my guess is that the appengine VM went to sleep, and served a 502 before the VM was up again. when VM came up (split-second later), got a 200.

if this is indeed happening, we should report it up to appengine team (i can handle this).

**the action item for this issue**:
reproduce this case, OR find out what happened from the logs.

**Comment by meyskens** [comment]
Looking at the amount of traffic I doubt the VM goes to sleep. Was this after a version update? Been having issues with those progressing those on other projects

**Comment by meyskens** [comment]
Closing as we didn't see it again
