### ISSUE TITLE
index.html: all chapter links on one line

### ISSUE THREAD

**Issue by s-mang** [womenwhogo/womenwhogo.org#5]
eg. (screenshot)
<img width="862" alt="screen shot 2017-11-14 at 4 07 01 pm" src="https://user-images.githubusercontent.com/2741356/32811684-e9e82e74-c955-11e7-8c29-2b684e16f1f0.png">

it would be awesome if we could massage the divs such that all the icon links appear on one line.
there are just a bunch of divs with `class="div-xs-3"` (container divs for icons) which should be now changed to `"div-xs-2"` in index.html, to accommodate more icons.

i'll get to this in a few days if no one wants to do it :).

**Comment by cdikibo** [comment]
I'll claim this

**Comment by s-mang** [comment]
yesss!!!! 🎉 you rock!

**Comment by s-mang** [comment]
<img width="935" alt="screen shot 2017-11-28 at 10 51 50 am" src="https://user-images.githubusercontent.com/2741356/33338220-33949ae2-d42a-11e7-803e-c40bdc29594f.png">
looks so good thanks again @cdikibo
