### ISSUE TITLE
wwg logo should be smaller

### ISSUE THREAD

**Issue by s-mang** [womenwhogo/womenwhogo.org#7]
wwg logo is too big, does not need to be so big.
Should probably be ~400x400px. currently is ~2kx2k

takes a while to load the first time (before browser cache), which does not look not great.

**Comment by cdikibo** [comment]
Maybe using kraken.io on the wwg logo will help with the loading

**Comment by s-mang** [comment]
oo fancy i've never heard of them before.
i think just reducing size should do the trick, but if you want to use kraken that sounds fine too!

woohoo @cdikibo thanks for your contributions

**Comment by s-mang** [comment]
Hey @cdikibo! Any update?
I'm happy to take this if you're running short on time :)

**Comment by nikhita** [comment]
Is this still something that we need? Happy to help with it. :)

/cc @carolynvs

**Comment by carolynvs** [comment]
This was fixed in eb8e1c1defabf2ac2739d47165387c1a7470aaf8. Closing, but thanks for asking about it! 💖
